admin/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('users', 'UserController');
Route::resource('agencies', 'AgenciesController');
Route::resource('tc', 'TrainingCentersController');

admin/resources/views/tc/create.blade.php
@extends('layouts.app')

@section('title', '| Add Training Center')

@section('content')

<section class="content-header">
    <h1>Agency</h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Training Center</a></li>
        <li class="active">Add</li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-6">
            @if (count($errors) > 0)
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
            <h1><i class='fa fa-user-plus'></i> Add Training Center</h1>
            <hr>

            {{ Form::open(array('route' => 'tc.store')) }}
            <div class="form-group">
                {{ Form::label('user_id', 'User ID') }}
                {{ Form::text('user_id', '', array('class' => 'form-control')) }}
            </div>

            <div class="form-group">
                {{ Form::label('contact_person_name', 'Contact Person') }}
                {{ Form::text('contact_person_name', '', array('class' => 'form-control')) }}
            </div>

            <div class="form-group">
                {{ Form::label('contact', 'Contact No.') }}
                {{ Form::text('contact', '', array('class' => 'form-control')) }}
            </div>
            
            <div class="form-group">
                {{ Form::label('address', 'Training Center Address') }}
                {{ Form::text('address', '', array('class' => 'form-control')) }}
            </div>

            {{ Form::submit('Add', array('class' => 'btn btn-primary')) }}

            {{ Form::close() }}

        </div>
    </div>
</section>

@endsection

admin/resources/views/tc/edit.blade.php
@extends('layouts.app')

@section('title', '| Edit Training Center')

@section('content')

<section class="content-header">
    <h1>Training Center</h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Training Center</a></li>
        <li class="active">Edit</li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-6">
            @if (count($errors) > 0)
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
            <h1><i class='fa fa-user-plus'></i> Edit Training Center</h1>
            <hr>
            {!! Form::model($tc, ['method' => 'PATCH','route' => ['tc.update', $tc->id]]) !!}
            <div class="form-group">
                {{ Form::label('user_id', 'User Id') }}
                {{ Form::text('user_id', null, array('class' => 'form-control')) }}
            </div>

            <div class="form-group">
                {{ Form::label('contact_person_name', 'Contact Person Name') }}
                {{ Form::text('contact_person_name', null, array('class' => 'form-control')) }}
            </div>

            <div class="form-group">
                {{ Form::label('contact', 'Contact') }}
                {{ Form::text('contact', null, array('class' => 'form-control')) }}
            </div>

            <div class="form-group">
                {{ Form::label('address', 'Address') }}
                {{ Form::text('address', null, array('class' => 'form-control')) }}
            </div>

            {{ Form::submit('Update', array('class' => 'btn btn-primary')) }}
            {!! Form::close() !!}

        </div>
    </div>
</section>

@endsection

admin/resources/views/tc/index.blade.php
@extends('layouts.app')

@section('title', '|  Training Centers')

@section('content')
<section class="content-header">
    <h1>
        Training Centers
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="{{ route('tc.index') }}">Training Centers</a></li>
        <li class="active">List</li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
            @endif
            <div class="table-responsive">
                <table class="table table-bordered table-striped">

                    <thead>
                        <tr>
                            <th>User Id</th>
                            <th>Contact Person Name</th>
                            <th>Contact</th>
                            <th>Address</th>
                            <th>Date/Time Added</th>
                            <th>Operations</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach ($tc as $tc_item)
                        <tr>

                            <td>{{ $tc_item->user_id }}</td>
                            <td>{{ $tc_item->contact_person_name }}</td>
                            <td>{{ $tc_item->contact  }}</td>
                            <td>{{ $tc_item->address  }}</td>
                            <td>{{ $tc_item->created_at->format('F d, Y h:ia') }}</td>
                            <td>
                                <a href="{{ route('tc.edit', $tc_item->id) }}" class="btn btn-info pull-left" style="margin-right: 3px;">Edit</a>

                                {!! Form::open(['method' => 'DELETE', 'route' => ['tc.destroy', $tc_item->id] ]) !!}
                                {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
                                {!! Form::close() !!}

                            </td>
                        </tr>
                        @endforeach
                    </tbody>

                </table>
                {!! $tc->render() !!}
            </div>

            <a href="{{ route('tc.create') }}" class="btn btn-success">Add Training Center</a>
        </div>
    </div>
</section>
@endsection

admin/resources/views/tc/view.blade.php
<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */